### ISSUE TITLE
No zip attached to the release

### ISSUE THREAD

**Issue by vyskoczilova** [helen/action-wordpress-plugin-deploy#67] opened 2021-04-05 19:32 UTC
**Describe the bug**

Deployed with action with "generate-zip" parameter, however, ended with "not found" issue:
![image](https://user-images.githubusercontent.com/3611726/113617002-252d1f00-9656-11eb-816d-53d8835b2e2f.png) used [this workflow](https://github.com/vyskoczilova/kybernaut-ic-dic/blob/master/.github/workflows/deploy.yml). Maybe related to SLUG used?

**Expected behavior**
 
Attach zip to the release - https://github.com/vyskoczilova/kybernaut-ic-dic/releases/tag/1.6.4

**Comment by jeffpaul** [comment] 2021-04-21 01:56
@helen direct link to failed `Upload release asset` is here: https://github.com/vyskoczilova/kybernaut-ic-dic/runs/2272301755?check_suite_focus=true.  Given that the GH repo is `kybernaut-ic-dic` but the SVN repo and `SLUG` environment variable is set to `woolab-ic-dic`, I wonder if that's the cause of failure here as @vyskoczilova hints at or something else?

**Comment by dinhtungdu** [comment] 2021-04-24 10:34
Hi @vyskoczilova, because you're using a custom slug, you need to use that slug in the upload release assets part

```
        SLUG: woolab-ic-dic
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{github.workspace}}/woolab-ic-dic.zip
        asset_name: woolab-ic-dic.zip
        asset_content_type: application/zip
```

**Comment by vyskoczilova** [comment] 2021-04-25 19:42
@dinhtungdu yeah, that makes sense. I'm pretty new with GitHub actions and haven't noticed that it works with different actions than the previous one so the slug is not passed.

**Comment by dinhtungdu** [comment] 2021-04-26 10:30
Closing this for now. Feel free to reopen/comment if need.

**Closed as completed by dinhtungdu** 2021-04-26 10:30 UTC
Labels: type:question, needs:feedback
