### ISSUE TITLE
Using WP boilerplate , unclear how to use this action with it

### ISSUE THREAD

**Issue by jasan-s** [helen/action-wordpress-plugin-deploy#64] opened 2021-01-30 01:54 UTC
I'm currently using https://github.com/DevinVinson/WordPress-Plugin-Boilerplate to build my wordpress plugin. I want to use this action to deploy to wordpress.org . However I'm unclear how exactly I can do that since there is no build scripts etc. Just the filter with all plugin files. Any guide to integrate this action with the above mentioned boilerplate would be greatly appreciated.   

If there is another boilerplate that works better with this action please offer suggestion as well.

**Comment by jeffpaul** [comment] 2021-02-09 21:04
@jasan-s if your plugin doesn't have a build process, then you can remove the build step from the action.  E.g., this code from our sample:
```
    - name: Build # Remove or modify this step as needed
      run: |
        npm install
        npm run build
```
If you run into issues getting this to work, then providing a link to your repo/failing action will help us better see what's going on... thanks!

**Comment by jeffpaul** [comment] 2021-03-22 22:01
@jasan-s did you have any further questions on the WP Deploy action or can we close out this issue?

**Comment by helen** [comment] 2021-08-17 02:37
I think this is realistically a duplicate of #16, based on the boilerplate structure.

**Closed as completed by helen** 2021-08-17 02:37 UTC
Labels: type:question, needs:feedback
